### PR TITLE
Remake website without nuxt framework

### PR DESCRIPTION
**Pull request by PyDario**
I remade this website in pure html/css and simple javascript.
As the website is mostly static, using a whole reactive framework is a bit overkill in my opinion.

This way, the site will load a lot faster and people that want to contribute don't have to install node.js or download all the node packages. It also allows for less overhead overall.

As it is now, the javascript-file only contains functions to load, sort and search the table and to display the change date at the bottom of the site.

### CODE REVIEW

**Comment by uberswe** [comment]
This would also make it easier to maintain as you pretty much eliminate dependabot alerts like #138

**Comment by PyDario** [comment]
In case you think about approving or even merging this, it would be swell if you marked this PR as "hacktoberfest-approved"

**Comment by uberswe** [comment]
There is also a similar site that popped up around the same time as this one without the bloat https://aclist.github.io/

Noticed it in the comments here https://www.reddit.com/r/linux_gaming/comments/q86qac/comment/hgnmdjg/

**Comment by Starz0r** [comment]
I've been mulling over this for a while, and it looks like a very high effort PR, and contains a lot of changes, but I don't yet know if they are necessarily worth it.

Let me explain a bit. Why did I choose Vue + Nuxt.js? I had already been learning Vue, and wanted to learn Nuxt.js for other projects. Nuxt.js provides me a way to turn most of the elements on the site, into static ones requiring no JavaScript to be run on the client's device, which makes it load all very fast, and under 250 KB. Choosing this also allows for standardize and better collaboration between other web developers, and makes it easy to maintain the entire project.

While I have nothing against the traditional HTML + JS, use what you need approach, it was obvious to me from the get go if I wanted to enable collaboration and ease of development, I should probably choose a framework. The site still loads fast, has minimal JavaScript, and does exactly what it needs to without any bloat. And if I should come to expanding the scope of the project (like building an API server), then that can easily be done trivially.

This brings me to this PR, which puts me in a precarious position. I do not think removing Nuxt from the project would make it any better ***at the moment***, but I'll reserve my judgement until later. But I do see some value and having an even lighter version of the site for those who might want it.

At the current moment, there are a few things stopping me from merging this.

1. The feature branch and the master branch have somewhat diverged in features and bug fixes added, so that would have to be caught up on again.
2. It erases all work done by other contributors thus far. These changes should be relegated into a subfolder in the `src` folder so that it can be included on the site properly without destroying the work of every other contributor.
3. As time goes on after this gets merged, it will have to be kept within parity to the main site, would you be willing to upkeep it even after it gets merged?

If you can satisfy these requirements, I won't feel so odd about merging it.

**Comment by PyDario** [comment]
@Starz0r Thank you for taking the time to check this PR.
Thank you for taking the time to answer my pull request. 

I think I understand where you're coming from. I still think using the framwork for a site like this is too much. However, I can see the beneifts of it. I already noticed myself that the initial loading experience isn't as snappy as your original. This gave an idea though. Maybe we can take the best of both worlds. 

The code is pretty simple, right? We could keep Vue's compiled html tablet, while serving the user only the simple javascript. That way, we'd have the benefit of a fast load-up, together with a smaller package size and human readable code, when someone inspects the page. I'd have to look more into how Vue works, however, as well as make a new project entirely to facility that.

**Comment by PyDario** [comment]
I'll close this Pull request, as the best solution would'nt be to rebuild it using pure javascript. Since the user always sees a static website, using something like PHP on server side, that preprocesses the html code would make more sense. Whether or not this will be eventually done, I'll leave it up to the maintainer.

**Pull request closed without merging**
