### PR TITLE
Add table to display individual game totals for each type of anti-cheat

### PR DESCRIPTION
**Pull request by Autofix**
The current top bar gives a general idea of the progress, but it isn't clear that anti-cheat like VAC, FairFight and PunkBuster are almost completely supported compared to the rest without looking through a long list.

It's close enough to be functional but the styling is not completely correct as I had to revert to a HTML table because I couldn't get the vue table to align correctly.

### CODE REVIEW

**Comment by Starz0r** [comment]
I like the idea behind this a lot, but I have a few critiques.

Right now it looks very visually cluttered to the point of information overload. It might be useful to try to keep information that may not be immediately important in a separate tab, or maybe hidden by default until hovered.

Also, despite several anti-cheats being merged into the “Other” category, I believe it's still useful to keep them separate, if possible, despite them only being used in a few, or even one game.

There is also a bug where if an entry has no Confirmed titles, this phantom “0” appears and makes it look worse.

This is overall a nice addition, but it needs a bit more work.

**Comment by Autofix** [comment]
I think it's a difference between the reasoning of why people are coming to the website. Is it to see if their specific game is supported and they just want to get to the list? Or is it for Linux compatibility progress in general where a table/graph for quick comparison is more useful? I'm not keen on hover, but I'll try some kind of dropdown or maybe simplify and integrate it into the top progress bar so it doesn't change the initial view too much.

I can easily separate the other ones, they just hadn't been separated out already in the large switch statement so I didn't want to change too much at once.

I'll have another go at the styling. I was just initially trying to get the concept working.

**Comment by Autofix** [comment]
The dropdown button seems to work ok as it doesn't interfere with the initial layout. If this still doesn't suit you I'll look into another way to simplify how the table is displayed.

I split out the other anti-cheats, they'll still need logos but I don't think that's part of this pull request. I'm also unsure about the 'Internal' category and if it should just list each individual game considering there's already a few that only have 1 game..

**Comment by Starz0r** [comment]
I think this looks way better now with the changes, so I'm going to go ahead and merge this. Thank you for the pull request!

**Review by Starz0r — APPROVED** [review]

**Pull request merged**
