### PR TITLE
Add Epic store ids

### PR DESCRIPTION
**Pull request by felipecrs**
I built a script for it, which I'm pushing in this PR. Feel free to remove it though. I separated in different commits to make it easier to review.

## Auto-matched

- Battlefield 2042 -> Battlefield™ 2042
- Valorant -> VALORANT
- Back 4 Blood -> Back 4 Blood
- Paladins -> Paladins
- Rainbow Six: Siege -> Rainbow Six Siege
- SMITE -> SMITE
- ARK: Survival Evolved -> ARK: Survival Evolved
- Dead By Daylight -> Dead by Daylight
- Insurgency: Sandstorm -> Insurgency: Sandstorm
- Rogue Company -> Rogue Company
- For Honor -> For Honor
- NARAKA: BLADEPOINT -> NARAKA: BLADEPOINT
- Genshin Impact -> Genshin Impact
- Rising Storm 2: Vietnam -> Rising Storm 2: Vietnam
- Knockout City -> Knockout City™
- Tom Clancy's Ghost Recon Wildlands -> Tom Clancy's Ghost Recon Wildlands
- Watch Dogs 2 -> Watch Dogs 2
- The Crew 2 -> The Crew 2
- CRSED: F.O.A.D. -> CRSED: F.O.A.D.
- STAR WARS™: Squadrons -> Star Wars Squadrons
- Diabotical -> Diabotical
- Splitgate -> Splitgate
- Tom Clancy's Ghost Recon Breakpoint -> Tom Clancy's Ghost Recon Breakpoint
- Worms Rumble -> Worms Rumble
- Outriders -> OUTRIDERS
- Spellbreak -> Spellbreak
- Conan Exiles -> Conan Exiles
- Mount & Blade II: Bannerlord -> Mount & Blade II: Bannerlord
- Warface -> Warface
- The Cycle: Frontier -> The Cycle: Frontier
- Trials Rising -> Trials Rising
- Far Cry 5 -> Far Cry 5
- Tom Clancy's The Division -> Tom Clancy's The Division
- PixARK -> PixArk
- Predator: Hunting Grounds -> Predator: Hunting Grounds
- Chivalry 2 -> Chivalry 2
- Killing Floor 2 -> Killing Floor 2
- Watch Dogs: Legion -> Watch Dogs: Legion
- Dauntless -> Dauntless
- League of Legends -> League of Legends
- Warframe -> Warframe
- Century: Age of Ashes -> Century: Age of Ashes
- Evil Dead: The Game -> Evil Dead: The Game
- Hood: Outlaws & Legends -> Hood: Outlaws & Legends

## Low confidence

- **(rejected)** Squad -> Squad Editor
- Phantasy Star Online 2 -> Phantasy Star Online 2 New Genesis
- iRacing -> iRacing - 3-month new membership
- Dying Light -> Dying Light Enhanced Edition
- **(rejected)** Post Scriptum -> Post Scriptum Modding SDK
- Heroes & Generals -> Heroes & Generals WWII
- **(rejected)** Atlas -> Atlas Mod Kit
- **(rejected)** Mordhau -> MORDHAU Editor
- **(rejected)** Crysis -> Crysis 2 Remastered
- **(rejected)** Insurgency -> Insurgency: Sandstorm - Mod Tools & Editor
- **(rejected)** Battlefield 2 -> Battlefield™ 2042
- **(rejected)** Killing Floor -> Killing Floor 2
- Battlefield V -> Battlefield V Definitive Edition

## Manually added

- Crysis -> Crysis Remastered
- Tom Clancy's The Division 2 -> The Division 2
- Star Wars: Battlefront (2015) -> STAR WARS™ Battlefront™ Ultimate Edition
- Star Wars: Battlefront II (2017) -> STAR WARS™ Battlefront™ II: Celebration Edition
- Grand Theft Auto Online

## Games which did not match

- **(rejected)** Squad -> Squad Editor
- **(rejected)** Post Scriptum -> Post Scriptum Modding SDK
- **(rejected)** Atlas -> Atlas Mod Kit
- **(rejected)** Mordhau -> MORDHAU Editor
- **(rejected)** Crysis -> Crysis 2 Remastered
- **(rejected)** Insurgency -> Insurgency: Sandstorm - Mod Tools & Editor
- **(rejected)** Battlefield 2 -> Battlefield™ 2042
- **(rejected)** Killing Floor -> Killing Floor 2
- Halo: The Master Chief Collection
- Apex Legends
- Halo Infinite
- PlayerUnknown's Battlegrounds
- Black Desert Online
- DayZ
- Destiny 2
- Hunt: Showdown
- Rust
- War Thunder
- 7 Days to Die
- New World
- Warhammer: Vermintide 2
- Escape from Tarkov
- ArmA 3
- Realm Royale
- Unturned
- PlanetSide 2
- DJMAX RESPECT V
- Plants vs. Zombies: Battle for Neighborville
- Hell Let Loose
- Bless Unleashed
- Pandemic Express - Zombie Escape
- SCUM
- JUMP FORCE
- DRAGON BALL FighterZ
- Enlisted
- Due Process
- Rec Room
- World War 3
- Survarium
- DRAGON BALL XENOVERSE 2
- Zero Hour
- Ironsight
- Totally Accurate Battlegrounds
- Counter-Strike: Global Offensive
- Counter-Strike: Global Offensive​
- Counter-Strike: Global Offensive​​
- Team Fortress 2
- Dota 2
- Call of Duty®: Black Ops III
- Garry's Mod
- SoulWorker
- Digimon Masters Online
- Sector's Edge
- Dirty Bomb
- Empyrion - Galactic Survival
- Call of Duty: Modern Warfare (2019)
- Call of Duty: Warzone
- Brawlhalla
- Combat Arms: Reloaded
- POLYGON
- Call of Duty Black Ops: Cold War
- Albion Online
- Counter-Strike: Source
- Crossout
- Battlefield 4
- Vampire: The Masquerade - Bloodhunt
- MapleStory
- Deadside
- Intruder
- Call of Duty
- Half-Life 2: Deathmatch
- The Mean Greens: Plastic Warfare
- ArmA 2
- Quake III Arena
- Call of Duty 2
- Battlefield 1
- Nuclear Dawn
- Pirates, Vikings, and Knights II
- Battlefield 1942
- Team Fortress Classic
- ARK: Survival of the Fittest
- The Isle
- Call of Duty: Black Ops
- Call of Duty 4: Modern Warfare
- Day of Defeat
- Chivalry: Medieval Warfare
- Pang Online
- The Ship: Murder Party
- Call of Duty: Black Ops II
- Monstrum 2
- No More Room in Hell
- Depth
- Quake 4
- Deathmatch Classic
- SWORD ART ONLINE Alicization Lycoris
- Foxhole
- Block N Load
- Titanfall
- KartRider
- Battlefield 3
- KovaaK 2.0
- Day of Defeat: Source
- Tower Wars
- Hurtworld
- Call of Duty: Ghosts
- Sword Art Online: Fatal Bullet
- Battlefield: Bad Company 2
- Cry of Fear
- Call of Duty: Modern Warfare 2
- Kritika:Reboot
- Half-Life Deathmatch: Source
- Beyond the Wire
- Lost Planet: Extreme Condition
- Rocket Arena
- Call of Duty: Modern Warfare 3
- Left 4 Dead 2
- Tower Unite
- Day of Infamy
- Black Squad
- Primal Carnage
- Honkai Impact 3rd
- Dungeon Defenders
- APB Reloaded
- Battlefield: Hardline
- Gears 5
- Call of Duty: World at War
- Quake Live
- Captain Tsubasa: Rise of New Champions
- TOXIKK
- ArmA 2: Operation Arrowhead
- LaTale
- Crysis: Warhead
- Call of Duty: WWII
- Nostale
- Homefront
- Call of Duty: Infinite Warfare
- PangYa
- Quantum League
- Blazing Sails
- Titanfall 2
- Lemnis Gate
- Grandchase
- Black Clover: Quartet Knights
- Nine to Five
- Lost Ark
- Archeage: Unchained
- Hired Ops
- Call of Duty: Vanguard
- Star Citizen
- Quake Champions
- Pavlov VR
- NARUTO TO BORUTO: SHINOBI STRIKER
- Myth of Empires
- Gunfire Reborn
- Elden Ring
- Tibia
- Will To Live Online
- Battlefleet Gothic: Armada 2
- SUPER PEOPLE
- Darwin Project
- Call of Duty: Black Ops 4
- BattleBit Remastered
- Vindictus
- Deceit
- Absolver
- EZ2ON REBOOT : R
- Closers
- Allods Online
- Fiesta Online
- Friday The 13th: The Game
- Super Animal Royale
- Fallout 76
- ANOTHER EDEN
- Overwatch
- Overwatch 2
- Path Of Titans
- Awesomenauts - the 2D moba
- Dungeon Fighter Online
- SCP: Secret Laboratory
- Midnight Ghost Hunt
- Rumble Fighter: Unleashed

## Observations

- Splitgate did not come with a slug (maybe because it was not released yet?)
- The Division had a weird namespace (`epic`, but all the other offerings had `impala`, so I used `impala`)

### CODE REVIEW

**Comment by felipecrs** [comment]
Oh boy, this was though.

**Comment by Curve** [comment]
iRacing -> iRacing - 3-month new membership
Post Scriptum -> Post Scriptum Modding SDK

These two don't look right to me, especially Post Scriptum, should we reject them too?

**Comment by Curve** [comment]
Also, would you mind removing the script?

I think I'd like to keep them out of the repo right now (I also have one for the steam games) however I might add them later to auto suggest new IDs through a workflow that runs on new game additions

**Comment by felipecrs** [comment]
> Great work!
> 
> iRacing -> iRacing - 3-month new membership Post Scriptum -> Post Scriptum Modding SDK
> 
> These two don't look right to me, especially Post Scriptum, should we reject them too?

- iRacing is fine: https://store.epicgames.com/en-US/p/iracing
- Removed Post Scriptum, thank you!



> Also, would you mind removing the script?

Done. Actually it was a really bad decision to make it in Bash, but I figured this out too late. If I were re-create it, I would use something like https://fusejs.io/ for matching the games.

**Comment by Curve** [comment]
> > Great work!
> > 
> > iRacing -> iRacing - 3-month new membership Post Scriptum -> Post Scriptum Modding SDK
> > 
> > These two don't look right to me, especially Post Scriptum, should we reject them too?
> 
> - iRacing is fine: https://store.epicgames.com/en-US/p/iracing
> - Removed Post Scriptum, thank you! (I updated the PR description)
> 
> > Also, would you mind removing the script?
> 
> Done. Actually it was a really bad decision to make it in Bash, but I figured this out too late. If I were re-create it, I would use something like https://fusejs.io/ for matching the games.

Yep sounds good! 
Thanks for your work :D

I'll look into automatic PR Creation for Game Additions soon ^^

**Comment by felipecrs** [comment]
You are welcome, thanks for the great AWACY initiative and for being so supportive!

**Comment by Curve** [comment]
> You are welcome, thanks for the great AWACY initiative and for being so supportive!

Always a pleasure ;)

**Pull request merged**
