### PR TITLE
Add Epic Game Store Ids tool

### PR DESCRIPTION
**Pull request by felipecrs**
This one you may like bettter. :)

### CODE REVIEW

**Comment by felipecrs** [comment]
https://user-images.githubusercontent.com/29582865/178120064-3d455fb8-512a-4153-b98c-2c57cc631385.mp4

**Comment by Curve** [comment]
Awesome, thanks!

I'll keep this PR open until I'm done with the workflow to automate this ^^

**Comment by D3SOX** [comment]
I'd suggest to use Inquirer instead of Enquirer, Enquirer doesn't get updated any more and Inquirer has TypeScript support

**Comment by felipecrs** [comment]
> I'd suggest to use Inquirer instead of Enquirer, Enquirer doesn't get updated any more and Inquirer has TypeScript support

Great suggestion, I will do it.

**Comment by felipecrs** [comment]
Done, and I also made several improvements. Inquirer misses a feature from Enquirer which was option hints. I used it to display the EGS link. But it's fine, I worked around it.

**Comment by Curve** [comment]
Alright, I've adjusted the PR a little bit (eslint, skip games that already have epic id set, ...) ^^

In case any games are missing their Epic ID and you want to add them you can simply clone this repository and run `yarn epic` :tada: 

Thanks a lot for you contribution!

**Pull request merged**
